<?php
/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 17/6/14
 * Time: 下午5:03
 */

namespace libs\Pay\WeChat;

use libs\Curl\LCurl;
use libs\Pay\LPayConfig;
use libs\Utils\Arrays;
use libs\Utils\ServerUtil;
use libs\Utils\Strings;
use libs\Utils\XMLUtil;
use libs\Validate\LValidator;

/**
 * Class LWechatPayApp.
 * 微信支付(APP支付通道)
 * @package libs\Pay\WebChat
 */
class LWechatPayApp extends LWechatPay
{

    protected function getTradeType()
    {
        return LPayConfig::WECHAT_TRADE_APP; // TODO: Change the autogenerated stub
    }

    protected function unifiedOrder($data)
    {
        $result = parent::unifiedOrder($data);
        if ($result) {
            if (isset($result['result_code']) && $result['result_code'] == 'SUCCESS') {
                $packageData = [
                    'appid' => $this->appId,
                    'partnerid' => $this->mchId,
                    'prepayid' => Arrays::get($result, 'prepay_id'),
                    'package' => 'Sign=WXPay',
                    'noncestr' => Strings::uuid(),
                    'timestamp' => time()
                ];
                $packageData['sign'] = $this->getSign($packageData);
                return $packageData;
            }
        }
        return false;
    }
}